server:
  port: 8082
  
eureka:
  instance: 
    hostname: localhost
    port: 8762
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
  circuit-breaker:
    instances:
      default:
        falhe-rate-threshold: 40
spring:
  application:
    name: patient-service
  config:
    import:
      - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: patient 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.co3n5hj6lnhk.sa-east-1.rds.amazonaws.com:5432/db_easediet
    username: postgres
    password: postgres153227%
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East
    serialization:
      FAIL_ON_EMPTY_BEANS: false