server:
  port: 9000
eureka:
  instance: 
    hostname: localhost
    port: 8762
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
spring:
  application:
    name: gateway
  jackson:
    default-property-inclusion: NON_NULL    
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      #   - id: diet-service
      #     uri: lb://DIET-SERVICE
      #     predicates:
      #       - Path=/diets/**
      #   - id: diet-service
      #     uri: lb://DIET-SERVICE
      #     predicates:
      #       - Path=/translate/**
      #   - id: diets-groups-service
      #     uri: lb://DIETS-GROUPS-SERVICE
      #     predicates:
      #       - Path=/diets-groups/**
      #   - id: nutritionist-service
      #     uri: lb://NUTRITIONIST-SERVICE
      #     predicates:
      #       - Path=/nutritionist/**
      #   - id: patient-service
      #     uri: lb://PATIENT-SERVICE
      #     predicates:
      #       - Path=/patient/**
      #   - id: payment-service
      #     uri: lb://PAYMENT-SERVICE
      #     predicates:
      #       - Path=/payment/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
jwt:
  secret: secretkey
  token:
    validity: 180000
