server:
  port: 9000
eureka:
  instance: 
    hostname: localhost
    port: 8762
  client:
    registerWithEureka: true
    fetchRegister: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: diet-service
          uri: lb://DIET-SERVICE
          predicates:
            - Path=/diets/**
        - id: diet-service
          uri: lb://DIET-SERVICE
          predicates:
            - Path=/translate/**
        - id: diets-groups-service
          uri: lb://DIETS-GROUPS-SERVICE
          predicates:
            - Path=/diets-groups/**
        - id: nutritionist-service
          uri: lb://NUTRITIONIST-SERVICE
          predicates:
            - Path=/nutritionist/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**